spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javanc?useSSL=false&serverTimezone=UTC
    username: root
    password: Duy@0382750958
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10