spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC}
    username: root
    password: ${DB_PASSWORD:Abc@12345}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:nguyenvana@gmail.com}
    password: ${MAIL_PASSWORD:abcdefgh}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your_google_client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret}
            redirect-uri: http://localhost:3000/oauth2/callback/google
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:your_facebook_client_id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:your_facebook_client_secret}
            redirect-uri: http://localhost:3000/oauth2/callback/facebook
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            authorization-uri: https://www.facebook.com/v18.0/dialog/oauth
            token-uri: https://graph.facebook.com/v18.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large)
jwt:
  sign_key: ${SIGN_KEY:69YzD+lBgYPdLvX4kkzhYF9IX2zZ1okqn1SWi3/Us3iIw8bUbu7FzoX2r4RVe+7V}
  expiry_time_token: 1000
  expiry_time_refreshToken: 10000
cloud:
  api_key: ${CLOUD_API_KEY}
  api_name: ${CLOUD_API_NAME}
  api_secret: ${CLOUD_API_SECRET}
